export const SITE = {
  website: "https://tommycardelo.com/",
  author: "Tommy Cardenas Lopez",
  profile: "https://tommycardelo.com/",
  desc: "Data Scientist & AI Engineer | Automation & ML systems",
  title: "Tommy CardeLo",
  ogImage: "og-image.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit post",
    url: "https://github.com/TomCardeLo/tommycardelo-portfolio/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Bogota",
};